# ===================================
#  List Behavior Config
# ===================================

title: system::lang.updates.title
list: ~/modules/system/models/pluginlist/columns.yaml
modelClass: System\Models\PluginList
noRecordsMessage: backend::lang.list.no_records
recordUrl: system/updates/details/:slug

toolbar:
    buttons: list_toolbar
